name: Build Rec

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: ðŸ”„ RÃ©cupÃ©ration du code
      uses: actions/checkout@v4

    - name: ðŸš€ Properties propertiesmanager-rec
      run: |
        cd /opt/propertiesmanager-connector
        java -jar propertiesmanager-java-connector-runner.jar UPDATE "propertiesmanager" "main" "rec" "${{ github.workspace }}/propertiesmanager-ui/public/config/config.json"
        java -jar propertiesmanager-java-connector-runner.jar UPDATE "propertiesmanager" "main" "rec" "${{ github.workspace }}/propertiesmanager-ui/public/config/keycloak.json"
        java -jar propertiesmanager-java-connector-runner.jar UPDATE "propertiesmanager" "main" "rec" "${{ github.workspace }}/propertiesmanager-api/src/main/resources/application.properties"
        cd ${{ github.workspace }}

    - name: Build site
      working-directory: propertiesmanager-ui
      run: |
        npm install
        npm run build
    - name: Build backend
      run: ./build-all.sh rec
    - name: Deploy site
      run: |
        rm -rf /opt/props/props-ui-rec
        mkdir -p /opt/props/props-ui-rec
        cp -r propertiesmanager-ui/build/* /opt/props/props-ui-rec/
    - name: Deploy API
      run: |
        mkdir -p /opt/props/props-api-rec
        cp propertiesmanager-api/target/*-runner.jar /opt/props/props-api-rec/props-api-runner.jar
        cp ${{ github.workspace }}/propertiesmanager-api/src/main/resources/application.properties /opt/props/props-api-rec/config/application.properties

        sudo systemctl restart quarkus-props-api-rec.service
