name: Build Dev

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: ðŸ”„ RÃ©cupÃ©ration du code
        uses: actions/checkout@v4

      - name: ðŸš€ DÃ©ploiement sur propertiesmanager-dev
        run: |
          cd /opt/propertiesmanager-connector
          java -jar propertiesmanager-java-connector-runner.jar UPDATE "propertiesmanager" "snapshot" "dev" "${{ github.workspace }}/propertiesmanager-ui/public/config/config.json"
          java -jar propertiesmanager-java-connector-runner.jar UPDATE "propertiesmanager" "snapshot" "dev" "${{ github.workspace }}/propertiesmanager-ui/public/config/keycloak.json"
          java -jar propertiesmanager-java-connector-runner.jar UPDATE "propertiesmanager" "snapshot" "dev" "${{ github.workspace }}/propertiesmanager-api/src/main/resources/application.properties"
          cd ${{ github.workspace }}

      - name: Build site
        working-directory: propertiesmanager-ui
        run: |
          npm install
          npm run build:dev
      - name: Build backend
        run: ./build-all.sh dev
      - name: Deploy site
        run: |
          rm -rf /opt/props/props-ui-dev
          mkdir -p /opt/props/props-ui-dev
          cp -r propertiesmanager-ui/build/* /opt/props/props-ui-dev/
      - name: Deploy API
        run: |
          mkdir -p /opt/props/props-api-dev
          cp propertiesmanager-api/target/*-runner.jar /opt/props/props-api-dev/props-api-runner.jar
          cp ${{ github.workspace }}/propertiesmanager-api/src/main/resources/application.properties /opt/props/props-api-dev/config/application.properties

          sudo systemctl restart quarkus-props-api-dev.service
